insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Beauty');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Tools');
insert into PowerUpCategories (Name) values ('Storage');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Wearable Tech');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Cooking Oils');
insert into PowerUpCategories (Name) values ('Clothing - Loungewear');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Spices & Seasonings');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Safety');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Clothing - Pants');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Home Appliances');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Grocery');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Clothing - Loungewear');
insert into PowerUpCategories (Name) values ('Clothing - Bags');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Meat Alternatives');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Footwear');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Clothing - Tops');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Tools');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Footwear');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Clothing - Tops');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Frozen Fruits');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Frozen Desserts');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Frozen Desserts');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Oils & Vinegars');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Seafood');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Deli Meats');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Baby');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home Appliances');
insert into PowerUpCategories (Name) values ('Food - Meat Substitutes');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Sides');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Clothing - Accessories');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Clothing - Tops');
insert into PowerUpCategories (Name) values ('Clothing - Accessories');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Frozen Meals');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Freezer');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Clothing - Pants');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Fresh Produce');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Smart Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Baking Goods');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Jams & Jellies');
insert into PowerUpCategories (Name) values ('Crafts');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Breakfast Foods');
insert into PowerUpCategories (Name) values ('Beauty');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Spreads');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Clothing');
insert into PowerUpCategories (Name) values ('Food - Frozen Meals');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Meats');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Confectionery');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Home Security');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Cereal');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Cooking Oils');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Wearable Tech');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Clothing - Shirts');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Cereal');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Clothing - Accessories');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Supplements');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Clothing');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Home Improvement');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Oils');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Wearable Tech');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Clothing - Shirts');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Dips');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Cereal');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Crafts');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Vegetarian');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Bathroom');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Grooming');
insert into PowerUpCategories (Name) values ('Food - Health Foods');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Pasta');
insert into PowerUpCategories (Name) values ('Food - Cheese');
insert into PowerUpCategories (Name) values ('Food - Seafood');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Clothing - Sweaters');
insert into PowerUpCategories (Name) values ('Food - Pasta');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Sides');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Health/Protein');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Beauty');
insert into PowerUpCategories (Name) values ('Food - Pasta');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Beauty');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Dressings');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Clothing - Accessories');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Pasta');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Computers');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Frozen Desserts');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Meats');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Canned Soups');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Footwear');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Home Appliances');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Clothing - Loungewear');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Seasonings');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Dressings');
insert into PowerUpCategories (Name) values ('Footwear');
insert into PowerUpCategories (Name) values ('Art Supplies');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Oils & Vinegars');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Jams & Jellies');
insert into PowerUpCategories (Name) values ('Food - Baking Goods');
insert into PowerUpCategories (Name) values ('Furniture');
insert into PowerUpCategories (Name) values ('Clothing - Shirts');
insert into PowerUpCategories (Name) values ('Food - Frozen Meals');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Clothing - Tops');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Seafood');
insert into PowerUpCategories (Name) values ('Food - Cereal');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Storage');
insert into PowerUpCategories (Name) values ('Food - Meal Kits');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Safety');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Footwear');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Confectionery');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Clothing - Sweaters');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Food - Canned Soups');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Supplements');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Clothing - Pants');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Freezer');
insert into PowerUpCategories (Name) values ('Food - Prepared Meals');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Food - Seafood');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Dried Fruits');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Bicycles');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Clothing - Loungewear');
insert into PowerUpCategories (Name) values ('Food - Oils');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Baby');
insert into PowerUpCategories (Name) values ('Food - Meat & Seafood');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Bicycles');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Food - Meat Substitutes');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Meal Kits');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Cheese');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Clothing - Skirts');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Prepared Meals');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Tools');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Baked Goods');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Prepared Meals');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Gaming');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Seafood');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Dairy Alternatives');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Breakfast Foods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Sports');
insert into PowerUpCategories (Name) values ('Food - Prepared Meals');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Food - Health/Protein');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Cheese');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Clothing - Footwear');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Clothing');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Supplements');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Smart Home');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Breakfast');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Food - Baking Goods');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Clothing - Dresses');
insert into PowerUpCategories (Name) values ('Food');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Food - Desserts');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Electronics');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Photography');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Beauty');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Frozen Vegetables');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Clothing - Outerwear');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Audio');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Food - Frozen Meals');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Art Supplies');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Pasta');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Dips');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Dips');
insert into PowerUpCategories (Name) values ('Food - Frozen Food');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Nuts');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Clothing - Activewear');
insert into PowerUpCategories (Name) values ('Food - Dairy');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Smart Home');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Garden');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Cereal');
insert into PowerUpCategories (Name) values ('Food - Salads');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Meat');
insert into PowerUpCategories (Name) values ('Baby');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Clothing - Shirts');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Oils & Vinegars');
insert into PowerUpCategories (Name) values ('Food - Prepared Foods');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Canned Goods');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Prepared Meals');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Food - Soups');
insert into PowerUpCategories (Name) values ('Food - Grains');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Food - Frozen');
insert into PowerUpCategories (Name) values ('Home Appliances');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Health');
insert into PowerUpCategories (Name) values ('Food - Cereals');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Food - Sauces');
insert into PowerUpCategories (Name) values ('Food - Spices');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Travel');
insert into PowerUpCategories (Name) values ('Toys');
insert into PowerUpCategories (Name) values ('Automotive');
insert into PowerUpCategories (Name) values ('Clothing - Accessories');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Clothing - Bottoms');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Smart Home');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Gaming');
insert into PowerUpCategories (Name) values ('Food - Condiments');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Clothing - Pants');
insert into PowerUpCategories (Name) values ('Clothing - Jumpsuits');
insert into PowerUpCategories (Name) values ('Kitchen');
insert into PowerUpCategories (Name) values ('Food - Baking');
insert into PowerUpCategories (Name) values ('Office');
insert into PowerUpCategories (Name) values ('Clothing - Loungewear');
insert into PowerUpCategories (Name) values ('Pets');
insert into PowerUpCategories (Name) values ('Food - Oils & Vinegars');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Bakery');
insert into PowerUpCategories (Name) values ('Home');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Fitness');
insert into PowerUpCategories (Name) values ('Books');
insert into PowerUpCategories (Name) values ('Accessories');
insert into PowerUpCategories (Name) values ('Outdoor');
insert into PowerUpCategories (Name) values ('Food - Vegetables');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Beverages');
insert into PowerUpCategories (Name) values ('Food - Produce');
insert into PowerUpCategories (Name) values ('Food - Snacks');
insert into PowerUpCategories (Name) values ('Food - Frozen Foods');
insert into PowerUpCategories (Name) values ('Food - Spices');
